# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1/design_1_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1 || ORIG_REF_NAME==design_1_axi_smc_1} -quiet] -quiet

# Block Designs: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/bd_6f02.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_2/bd_6f02_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_3/bd_6f02_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_4/bd_6f02_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/bd_6f02_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/bd_6f02_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_7/bd_6f02_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_8/bd_6f02_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_9/bd_6f02_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_10/bd_6f02_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_11/bd_6f02_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_12/bd_6f02_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_rst_ps7_0_50M_1/design_1_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_1 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_topserver_axi_0_8/design_1_topserver_axi_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_topserver_axi_0_8 || ORIG_REF_NAME==design_1_topserver_axi_0_8} -quiet] -quiet

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_topserver_axi_0_8/src/fifo_generator_8/fifo_generator_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_8 || ORIG_REF_NAME==fifo_generator_8} -quiet] -quiet

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_topserver_axi_0_8/src/fifo_generator_7/fifo_generator_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_7 || ORIG_REF_NAME==fifo_generator_7} -quiet] -quiet

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_topserver_axi_0_8/src/fifo_generator_1/fifo_generator_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] -quiet

# IP: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_topserver_axi_0_8/src/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/bd_6f02_s00a2s_0_ooc.xdc

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/bd_6f02_sarn_0_ooc.xdc

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_7/bd_6f02_srn_0_ooc.xdc

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_8/bd_6f02_sawn_0_ooc.xdc

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_9/bd_6f02_swn_0_ooc.xdc

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_10/bd_6f02_sbn_0_ooc.xdc

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_11/bd_6f02_m00s2a_0_ooc.xdc

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/ooc.xdc

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1 || ORIG_REF_NAME==design_1_axi_smc_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_1/design_1_rst_ps7_0_50M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_1 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_topserver_axi_0_8/src/fifo_generator_8/fifo_generator_8.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_8 || ORIG_REF_NAME==fifo_generator_8} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_topserver_axi_0_8/src/fifo_generator_7/fifo_generator_7.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_7 || ORIG_REF_NAME==fifo_generator_7} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_topserver_axi_0_8/src/fifo_generator_1/fifo_generator_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/ip/design_1_topserver_axi_0_8/src/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/kevin/Desktop/kyber_proj/kyber_proj.gen/sources_1/bd/design_1/design_1_ooc.xdc
